name: Check Duplicates Entered

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run JS script
        run: node scripts/code_quality.js

      - name: Check script result
        run: echo "::set-output name=SCRIPT_RESULT::$(node scripts/code_quality.js)"

      - name: Fail if script returns false
        run: exit ${{ steps.check-script.outputs.SCRIPT_RESULT == 'false' }}
