name: Check Sorted

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
jobs:
  check-names-sorted:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if files are sorted
        run: npm run check-sorted
